# Workflow for Forever Engine, based on Codename's workflow, except merged into one file, 'cause why not? :]
# Mashed together by Doggo, archival by BeastlyGabi.
# Check out Codename, by YoshiCrafter29, here: https://github.com/YoshiCrafter29/CodenameEngine

name: main

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  buildLinux:
    name: Linux build
    runs-on: ubuntu-latest

    steps:
    - name: Pulling new commit
      uses: actions/checkout@main

    - name: Setting up Haxe
      uses: krdlab/setup-haxe@master
      with:
        haxe-version: 4.2.5

    - name: Restore existing build cache
      uses: actions/cache@main
      with:
        key: cache-build-linux
        path: |
          .haxelib/
          export/release/linux/haxe/
          export/release/linux/obj/
        restore-keys: |
          cache-build-linux

    - name: Installing or updating libraries
      run: |
        haxelib setup ~/haxelib
        haxelib install hxcpp
        haxelib install hmm
        haxelib run hmm install

    - name: Building
      run: haxelib run lime build Project.xml linux -release

    - name: Uploading build artifact
      uses: actions/upload-artifact@main
      with:
        name: Forever-Engine
        path: "export/release/linux/bin"

    - name: Uploading executable artifact
      uses: actions/upload-artifact@main
      with:
        name: Update-Linux
        path: "export/release/linux/bin/Forever-Engine"

  buildWindows:
    name: Windows build
    runs-on: windows-latest

    steps:
    - name: Pulling new commit
      uses: actions/checkout@main

    - name: Setting up Haxe
      uses: krdlab/setup-haxe@master
      with:
        haxe-version: 4.2.5

    - name: Restore existing build cache
      uses: actions/cache@main
      with:
        key: cache-build-windows
        path: |
          .haxelib/
          export/release/windows/haxe/
          export/release/windows/obj/
        restore-keys: |
          cache-build-windows

    - name: Installing or updating libraries
      run: |
        haxelib setup C:/haxelib
        haxelib install hxcpp
        haxelib install hmm
        haxelib run hmm install

    - name: Building
      run: haxelib run lime build Project.xml windows -release

    - name: Uploading build artifact
      uses: actions/upload-artifact@main
      with:
        name: Forever-Engine
        path: "export/release/windows/bin"

    - name: Uploading executable artifact
      uses: actions/upload-artifact@main
      with:
        name: Update-Windows
        path: "export/release/windows/bin/Forever-Engine"

  buildMac:
    name: macOS build
    runs-on: macos-latest

    steps:
    - name: Pulling new commit
      uses: actions/checkout@main

    - name: Setting up Haxe
      uses: krdlab/setup-haxe@master
      with:
        haxe-version: 4.2.5

    - name: Restore existing build cache
      uses: actions/cache@main
      with:
        key: cache-build-mac
        path: |
          .haxelib/
          export/release/mac/haxe/
          export/release/mac/obj/
        restore-keys: |
          cache-build-mac

    - name: Installing or updating libraries
      run: |
        haxelib setup ~/haxelib
        haxelib install hxcpp
        haxelib install hmm
        haxelib run hmm install

    - name: Building
      run: haxelib run lime build Project.xml mac -release

    - name: Uploading build artifact
      uses: actions/upload-artifact@main
      with:
        name: Forever-Engine
        path: "export/release/mac/bin"

    - name: Uploading executable artifact
      uses: actions/upload-artifact@main
      with:
        name: Update-macOS
        path: "export/release/mac/bin/Forever-Engine"
